# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e8ac43dcb5fe019e0431aec3d7a8e63fff53cf0d92d30799c754bf9c12744ba05a77cd99a5148af32ce508a56ec06ee878f79ec243e35198ecc5d55e91804e7

test:
  secret_key_base: b09abb9c9ceffdc62e45a324797c7ab068a8924879c7e58d0b083ca50d875457c601fc22c3044b9f30a05ec4a148df077c01d13564083ddbbc7ea1abea9ffc56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
